import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from '@/components/Nav'
import Footer from '@/components/Footer'
import { ThemeProvider } from '@/components/theme-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={`${inter.className}`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <div className='flex flex-col lg:max-w-3xl md:max-w-2xl max-w-xl mx-auto mt-5'>
            <Nav />
          </div>
          {children}
          <div className='flex flex-col lg:max-w-3xl max-w-xl lg:mx-auto md:mx-auto mx-2 my-5'>
            <Footer />
          </div>
        </ThemeProvider>
      </body>

    </html>
  )
}
